### ISSUE TITLE
No TimeoutError recover for notification

### ISSUE THREAD

**Issue by flifloo** [flifloo/TelegramEDT#8]
```
{ERROR}[2019-10-01 23:42:16,231]: aiogram.dispatcher.dispatcher | Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 285, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/aiogram/bot/bot.py", line 94, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.7/site-packages/aiogram/bot/base.py", line 184, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, timeout=self.timeout, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogram/bot/api.py", line 97, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 857, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Comment by flifloo** [comment]
Fix on commit [49221e9](https://github.com/flifloo/repo/commit/49221e9553c463edd0386194b429e0e99e678645)
